# Documentation page information
site_name: SparkFun Hookup Guides
site_description: A list of all the SparkFun hookup guides hosted by GitHub pages
site_url: https://test.sparkfun.com
site_author: SparkFun Electronics

repo_url: https://github.com/santaimpersonator/sparkfun.github.io
repo_name: santaimpersonator/sparkfun.github.io

copyright:
  Copyright 2024 - <a href="https://www.sparkfun.com/" target="_blank" rel="noopener">SparkFun Electronics&#174;<br>
  <a href="https://goo.gl/maps/vkstCpQZW6jZMjzYA" target="_blank" rel="noopener">6333 Dry Creek Parkway, Niwot, Colorado 80503</a>

# Default edit/view actions to "main" branch, instead of "master"
edit_uri: blob/main/docs/


# Configuration for webpage theme
theme:
  # Theme: https://squidfunk.github.io/mkdocs-material/
  name: material

  # Icon in Browser Tab (must be square img - i.e. 32x32 pixels)
  favicon: img/sfe_logo_sq.png

  # Page Font
  font:
    text: Roboto
    code: Roboto Mono
  

  # Features to Include (ref. theme documentation)
  features:

    # Enables tabs for navigating the website
    - navigation.tabs

    # Keeps tabs visible in the header when scrolling
    - navigation.tabs.sticky

    # Renders path for page navigation at the top of the page (makes page navigation more mobile friendly)
    - navigation.path


  # Adds light/dark theme to the webpage
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      accent: red
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: red
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode    


  # Configures icons
  icon:
    # Sets homepage icon
    logo: sparkfun-logo

    # Sets repo icon to GitHub icon
    repo: fontawesome/brands/github

    # Admonition Icons (callout boxes)
    admonition:
      note: simple/github


  # Adds overrides for icons, html, etc.
  custom_dir: overrides



# Included MkDocs plugins
# Add the installation of any new plugins to the ./github/workflows/mkdocs.yml file also
plugins:

  # Allows formatting (code block, icons, etc.) in headings and titles
  - typeset

  # Redirects page navigation
  # - redirects:
  #     redirect_maps:
  #       'index.md': 'introduction.md'

  # # Add revision date
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: timeago

  # # Add git committers at the bottom of the page
  # - git-committers:
  #     repository: sparkfun/SparkFun_RTK_mosaic-X5
  #     branch: main

  # # Add git authors at the bottom of the page
  # - git-authors
  
  # Enables use of Git submodules and larger code base
  - monorepo
  
  # # Enables improved security for external links
  # - privacy:
  #     # Disables cache mechanism, so that external assets can be updated during rebuilds
  #     cache: false

  #     # # Allows for external assets to be used
  #     # assets: true
  #     # assets_fetch: true

  #     # Provide domains for assets that are retrieved from external sites
  #     assets_include:
  #       - https://docs.sparkfun.com/*
      
  #     # External links open in a new tab
  #     links_attr_map:
  #       target: _blank
  #     links_noopener: true

  # # Optimizes media files (*.png and *.jpg)
  # - optimize:
  #     # Specify directory; otherwise, multiple instances are created (.cache/plugins and .cache/plugin)
  #     cache_dir: .cache/plugins/optimize

  #     # Default values (from auto-complete)
  #     # ------------------------------
  #     # enabled: true
  #     # cache: true
  #     # cache_dir: .cache/plugins/optimize
  #     # optimize_png: true
  #     # optimize_png_speed: 4
  #     # optimize_png_strip: true
  #     # optimize_jpg: true
  #     # optimize_jpg_quality: 60
  #     # optimize_jpg_progressive: true
  #     # print_gain: true
  #     # print_gain_summary: true


# Included Markdown extensions
markdown_extensions:
  
  # Allows admonition extension to collapse the call-out boxes
  - pymdownx.details
  
  # Allows the use of tabs in the document
  - pymdownx.tabbed:
      alternate_style: true 
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  
  # Allows the use of admonition/call-out boxes
  - admonition
  
  # Allows the use of HTML syntax in Markdown elements
  - attr_list
  
  # Allows the use of bundled and custom icons and emojis
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons



extra:
  # Configures the hyperlink for the logo in the header
  homepage: https://www.sparkfun.com

  # Configures social icons in the footer
  social:
    - icon: sfe-logo
      link: https://www.sparkfun.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/sparkfun

  # Configures Google Analytics
  # analytics:
  #   provider: google
  #   property: G-7Y7EYCZVC1



# Configures cascade styling sheet
extra_css:
  - stylesheet/extra.css


# Custom Javascripts
extra_javascript:
  # Enables support for jquery to pull repo data from gsg.json
  - https://code.jquery.com/jquery-3.6.0.min.js
  - javascript/tutorial-list.js


# Configures webpage navigation
nav:
  - index.md
